### ISSUE TITLE
Error acessing FlexObjects plugin configuration from Admin

### ISSUE THREAD

**Issue by NicoHood** [trilbymedia/grav-plugin-flex-objects#108]
When trying to access http://localhost:8000/de/admin/plugins/flex-objects (The Flex Plugin overview from admin panel) I get the following error:

```
An exception has been thrown during the rendering of a template ("Cannot load blueprint blueprints://flex-objects/pages.yaml: Loop detected while extending blueprint file '/<removed>/user/themes/quark/blueprints/default.yaml'").
```

This does only happen with the flex plugin, no other plugin.
* Flex 1.0.2
* Admin 1.10.3
* Grav 1.7.5

**Comment by mahagr** [comment]
Unfortunately, I cannot reproduce this one. Must be related to your page template somehow, have you customized it?

**Comment by NicoHood** [comment]
I am using the template from quark theme:
https://github.com/getgrav/grav-theme-quark/blob/develop/blueprints/default.yaml

This is also causing the issue. So it will be broken for many users, as it is the default theme.

**Comment by mahagr** [comment]
I'm using Quark as well and there are no issues for me.

**Comment by NicoHood** [comment]
You can reproduce this plugin by adding my [grav seo plugin](https://github.com/NicoHood/grav-plugin-seo) at the latest commit.

The bug occurs because of:
```
    public $features = [
        'blueprints' => 0, // Use priority 0
    ];
```

**Even if the plugin is disabled, the error occurs (ouch!)**

**Comment by mahagr** [comment]
Must be this: https://github.com/NicoHood/grav-plugin-seo/blob/master/blueprints/default.yaml#L1

I will need to check it out.

**Comment by mahagr** [comment]
@NicoHood I think I found the issue. If you move the page blueprints (or all files/folders) into `blueprints/pages` in the plugin, everything will work.

That said, I think this is a bug and should be fixed.

**Comment by mahagr** [comment]
PS: Disabled plugins will not do anything anymore. They are fully disabled and shouldn't cause errors like this anymore.

**Comment by NicoHood** [comment]
Were did the bug got fixed? In grav 1.7.16 this issue still exists! And the quark theme also did not get fixed yet:

https://github.com/getgrav/grav-theme-quark/blob/develop/blueprints/default.yaml

**Comment by NicoHood** [comment]
Please reopen this issue
